/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zoo_animals.view;

import com.mycompany.zoo_animals.model.Aerial;
import com.mycompany.zoo_animals.model.Habitat;
import com.mycompany.zoo_animals.service.IAerialService;
import javax.swing.text.PlainDocument;

/**
 *
 * @author santiagomanchola
 */
public class GUIEditAerial extends javax.swing.JFrame {
    
    private IAerialService aerialService;
    private com.mycompany.zoo_animals.service.IHabitatService habitatService;
    private java.util.List<Habitat> habitats = new java.util.ArrayList<>();

    /**
     * Creates new form GUIEditAerial
     */
    public GUIEditAerial(IAerialService aerialService) {
        this(aerialService, new com.mycompany.zoo_animals.service.HabitatService());
    }

    public GUIEditAerial(IAerialService aerialService, com.mycompany.zoo_animals.service.IHabitatService habitatService) {
        this.aerialService = aerialService;
        this.habitatService = habitatService;
        refreshHabitats();
        initComponents();
        setLocationRelativeTo(null);
        setFieldsEditable(false);
        setupFieldValidations();
        
        inputSearch.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                clearFields();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                clearFields();
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                clearFields();
            }
        });
    }

    @Override
    public void setVisible(boolean b) {
        if (b) {
            refreshHabitats(); 
        }
        super.setVisible(b);
    }
    
    private void refreshHabitats() {
        if (habitatService != null) {
            habitats = habitatService.getAll();
        } else {
            habitats = new java.util.ArrayList<>();
        }
        if (habitatComboBox != null) {
            java.util.List<String> names = new java.util.ArrayList<>();
            names.add("Ninguno");
            habitats.forEach(h -> names.add(h.getName()));
            habitatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(names.toArray(new String[0])));
            habitatComboBox.setSelectedIndex(0);
        }
    }

    private void setFieldsEditable(boolean editable) {
        nameInput.setEditable(editable);
        nameInput.setFocusable(editable);

        weightInput.setEditable(editable);
        weightInput.setFocusable(editable);


        wingspanInput.setEditable(editable);
        wingspanInput.setFocusable(editable);

    if (habitatComboBox != null) {
        habitatComboBox.setEnabled(editable); 
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnClose = new javax.swing.JToggleButton();
        btnEdit = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        weightInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
    birthDateInput = new javax.swing.JTextField();
    birthDateInput.setEditable(false);
    birthDateInput.setFocusable(false);
    birthDatePickerBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        wingspanInput = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    habitatComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar animal aereo");

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar");
        btnEdit.setToolTipText("");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        idLabel.setText("Identificador");

        idInput.setEditable(false);
        idInput.setFocusable(false);

        jLabel1.setText("Nombre");

        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        jLabel2.setText("Peso");

        jLabel3.setText("Fecha de nacimiento");
        birthDatePickerBtn.setText("\uD83D\uDCC5");
        birthDatePickerBtn.setToolTipText("Seleccionar fecha");
        birthDatePickerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var chosen = DatePickerUtil.pickDate(GUIEditAerial.this, parseDateSafely(birthDateInput.getText()));
                if (chosen != null) birthDateInput.setText(chosen.toString());
            }
        });

        jLabel4.setText("Envergadura");

        jLabel5.setText("Hábitat");
        {
            java.util.List<String> names = new java.util.ArrayList<>();
            names.add("Ninguno");
            if (habitats != null) habitats.forEach(h -> names.add(h.getName()));
            habitatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(names.toArray(new String[0])));
            habitatComboBox.setSelectedIndex(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(habitatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wingspanInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(birthDateInput)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthDatePickerBtn))
                            .addComponent(weightInput, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameInput, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idInput, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(birthDatePickerBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wingspanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(habitatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnEdit))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void setupFieldValidations() {

    ((PlainDocument) nameInput.getDocument()).setDocumentFilter(new TextOnlyDocumentFilter());
    
    ((PlainDocument) weightInput.getDocument()).setDocumentFilter(new NumericDocumentFilter());
    ((PlainDocument) wingspanInput.getDocument()).setDocumentFilter(new NumericDocumentFilter());
    
    ((PlainDocument) idInput.getDocument()).setDocumentFilter(new AlphanumericDocumentFilter());
    
    nameInput.setToolTipText("Solo letras y espacios");
    weightInput.setToolTipText("Solo números (ejemplo: 12.5)");
    wingspanInput.setToolTipText("Solo números (ejemplo: 2.5)");
    idInput.setToolTipText("Solo letras y números");
}
    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed


    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            refreshHabitats(); 
            String id = inputSearch.getText().trim();

            if (id.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor ingrese un ID.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            aerialService.getById(id).ifPresentOrElse(aerial -> {
                idInput.setText(aerial.getId());
                nameInput.setText(aerial.getName());
                weightInput.setText(String.valueOf(aerial.getWeightKg()));
                birthDateInput.setText(aerial.getBirthDate().toString());
                wingspanInput.setText(String.valueOf(aerial.getWingspan()));
                if (aerial.getHabitat() != null) {
                    Habitat h = aerial.getHabitat();
                    int idx = 0;
                    for (int i = 0; i < habitats.size(); i++) {
                        if (habitats.get(i).getName().equals(h.getName())) { idx = i + 1; break; }
                    }
                    habitatComboBox.setSelectedIndex(idx);
                } else {
                    habitatComboBox.setSelectedIndex(0);
                }
                setFieldsEditable(true);
                habitatComboBox.setEnabled(true);

                javax.swing.JOptionPane.showMessageDialog(this,
                    "Animal encontrado y campos poblados.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            }, () -> {
                clearFields();
                javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontró un animal con ID " + id,
                    "Error de búsqueda",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            });

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error de búsqueda",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         try {
            Habitat habitat;
            int sel = habitatComboBox.getSelectedIndex();
            if (sel <= 0) {
                habitat = null;
            } else {
                habitat = habitats.get(sel - 1);
            }
            Aerial aerial = new Aerial(
                idInput.getText().trim(),
                nameInput.getText().trim(),
                Double.parseDouble(weightInput.getText().trim()),
                java.time.LocalDate.parse(birthDateInput.getText().trim()),
                Double.parseDouble(wingspanInput.getText().trim()),
                habitat
            );

            aerialService.update(aerial);

            javax.swing.JOptionPane.showMessageDialog(this,
                "Animal actualizado correctamente.",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al actualizar: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void clearFields() {
        idInput.setText("");
        nameInput.setText("");
        weightInput.setText("");
        birthDateInput.setText("");
        wingspanInput.setText("");
    if (habitatComboBox != null) habitatComboBox.setSelectedIndex(0);

        setFieldsEditable(false);
    }
    
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private java.time.LocalDate parseDateSafely(String txt) {
        try { if (txt == null || txt.isBlank()) return null; return java.time.LocalDate.parse(txt.trim()); } catch (Exception e) { return null; }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthDateInput;
    private javax.swing.JButton birthDatePickerBtn;
    private javax.swing.JToggleButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> habitatComboBox;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField weightInput;
    private javax.swing.JTextField wingspanInput;
    // End of variables declaration//GEN-END:variables
}
