package com.mycompany.zoo_animals.view;

import com.mycompany.zoo_animals.model.Aerial;
import com.mycompany.zoo_animals.model.Aquatic;
import com.mycompany.zoo_animals.service.AerialService;
import com.mycompany.zoo_animals.service.AquaticService;
import com.mycompany.zoo_animals.service.IAerialService;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.SwingConstants;

/**
 *
 * @author santiagomanchola
 */
public class GUIGetAerial extends javax.swing.JFrame implements IActualizable{

    private IAerialService aerialService;

    /**
     * Creates new form GUIGetAerial
     */
    public GUIGetAerial(IAerialService aerialService) {
        this.aerialService = aerialService;
        initComponents();
        setLocationRelativeTo(null);
        aerialTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        int[] widths = {90, 120, 60, 160, 100, 165};
        for (int i = 0; i < widths.length; i++) {
            aerialTable.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
        }
        applyRightAlignment();
        adjustSizeToTable();
        
                //Me registro como observador
        ((AerialService) aerialService).addObserver(this);

        // Cargo datos iniciales
        actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        aerialTable = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado animales aereos");

        aerialTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre", "Peso", "Fecha de nacimiento", "Envergadura", "Habitat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(aerialTable);

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnList.setText("Listar");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnList)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnList))
                .addContainerGap())
        );

    pack(); 
    }// </editor-fold>//GEN-END:initComponents

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        actualizar();
    }//GEN-LAST:event_btnListActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

         @Override
    public void actualizar() {
        List<Aerial> aerials = aerialService.getAll();
        DefaultTableModel model = (DefaultTableModel) aerialTable.getModel();

        model.setRowCount(0);

        for (Aerial a : aerials) {
            model.addRow(new Object[]{
                a.getId(),
                a.getName(),
                a.getWeightKg(),
                a.getBirthDate(),
                a.getWingspan(),
                a.getHabitat()
            });
        }
    }
    
    private void adjustSizeToTable() {
        int totalWidth = 0;
        for (int i = 0; i < aerialTable.getColumnCount(); i++) {
            totalWidth += aerialTable.getColumnModel().getColumn(i).getPreferredWidth();
        }
        int headerHeight = aerialTable.getTableHeader().getPreferredSize().height;
        int visibleRows = Math.min(Math.max(aerialTable.getRowCount(), 6), 12);
        int rowHeight = aerialTable.getRowHeight();
        int tableHeight = headerHeight + (visibleRows * rowHeight) + 4;
        java.awt.Dimension d = new java.awt.Dimension(totalWidth + 40, tableHeight + 70);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(d.width - 40, tableHeight));
        pack();
        setLocationRelativeTo(null);
    }

    private void applyRightAlignment() {
        DefaultTableCellRenderer right = new DefaultTableCellRenderer();
        right.setHorizontalAlignment(SwingConstants.RIGHT);
        for (int i = 0; i < aerialTable.getColumnCount(); i++) {
            aerialTable.getColumnModel().getColumn(i).setCellRenderer(right);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aerialTable;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
