/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zoo_animals.view;

import com.mycompany.zoo_animals.model.Aerial;
import com.mycompany.zoo_animals.service.IAerialService;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author santiagomanchola
 */
public class GUIGetAerialById extends javax.swing.JFrame {

    private IAerialService aerialService;
    private Aerial currentAerial;

    /**
     * Creates new form GUIGetAerialById
     */
    public GUIGetAerialById(IAerialService aerialService) {
        this.aerialService = aerialService;
        initComponents();
        setLocationRelativeTo(null);
        styleComponents();

        searchInput.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                clearFields();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                clearFields();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                clearFields();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        weightInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        birthDateInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        wingspanInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        habitatAreaInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        climateInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        habitatNameInput = new javax.swing.JTextField();
        cleanBtn = new javax.swing.JButton();
        computeBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar animal aereo");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        idLabel.setText("Identificador");

        idInput.setEditable(false);
        idInput.setFocusable(false);

        jLabel1.setText("Nombre");

        nameInput.setEditable(false);
        nameInput.setEnabled(false);
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        weightInput.setEditable(false);
        weightInput.setEnabled(false);

        jLabel3.setText("Fecha de nacimiento");

        birthDateInput.setEditable(false);
        birthDateInput.setEnabled(false);

        jLabel4.setText("Envergadura");

        wingspanInput.setEditable(false);
        wingspanInput.setEnabled(false);

        jLabel2.setText("Peso");

        jLabel6.setText("Area Habitat");

        habitatAreaInput.setEditable(false);
        habitatAreaInput.setEnabled(false);
        habitatAreaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitatAreaInputActionPerformed(evt);
            }
        });

        jLabel7.setText("Clima Habitat");

        climateInput.setEditable(false);
        climateInput.setEnabled(false);
        climateInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                climateInputActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre Habitat");

        habitatNameInput.setEditable(false);
        habitatNameInput.setEnabled(false);

        cleanBtn.setText("Limpiar");
        cleanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanBtnActionPerformed(evt);
            }
        });

        computeBtn1.setText("Calcular cuidado");
        computeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(habitatNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(computeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cleanBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(habitatAreaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(climateInput, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(wingspanInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                        .addComponent(birthDateInput, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(weightInput, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nameInput, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(habitatNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(habitatAreaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(climateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(computeBtn1)
                    .addComponent(cleanBtn))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(weightInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birthDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wingspanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addContainerGap(83, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            String id = searchInput.getText().trim();
            if (id.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Por favor ingresa un ID.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            var optionalAerial = aerialService.getById(id);
            optionalAerial.ifPresentOrElse(aerial -> {
                this.currentAerial = aerial;

                idInput.setText(aerial.getId());
                nameInput.setText(aerial.getName());
                weightInput.setText(String.valueOf(aerial.getWeightKg()));
                birthDateInput.setText(aerial.getBirthDate().toString());
                wingspanInput.setText(String.valueOf(aerial.getWingspan()));
                if (aerial.getHabitat() != null) {
                    habitatNameInput.setText(aerial.getHabitat().getName());
                    habitatAreaInput.setText(String.valueOf(aerial.getHabitat().getAreaM2()));
                    climateInput.setText(aerial.getHabitat().getClimate());
                } else {
                    habitatNameInput.setText("Ninguno");
                    habitatAreaInput.setText("NA");
                    climateInput.setText("NA");
                }

                javax.swing.JOptionPane.showMessageDialog(this,
                        "Animal encontrado.",
                        "Éxito",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }, () -> {
                this.currentAerial = null;
                clearFields();
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se encontró un animal con ID " + id,
                        "Error de búsqueda",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            });
        } catch (Exception e) {
            this.currentAerial = null;
            javax.swing.JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Animal no encontrado",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void clearFields() {
        this.currentAerial = null;
        idInput.setText("");
        nameInput.setText("");
        weightInput.setText("");
        birthDateInput.setText("");
        wingspanInput.setText("");
        habitatNameInput.setText("");
        habitatAreaInput.setText("");
        climateInput.setText("");
    }

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void habitatAreaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitatAreaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitatAreaInputActionPerformed

    private void climateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_climateInputActionPerformed

    private void cleanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanBtnActionPerformed
        clearFields();
    }//GEN-LAST:event_cleanBtnActionPerformed

    private void computeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBtn1ActionPerformed
        if (currentAerial == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Primero debes buscar un animal.",
                    "Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double careIndex = currentAerial.calculateCareIndex();

            javax.swing.JOptionPane.showMessageDialog(this,
                    String.format("Animal: %s\nÍndice de cuidado: %.2f puntos",
                            currentAerial.getName(),
                            careIndex),
                    "Índice de Cuidado",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al calcular el índice de cuidado: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_computeBtn1ActionPerformed

    private void styleComponents() {
        Font base = idLabel.getFont();
        Font bold = base.deriveFont(Font.BOLD);
        idLabel.setFont(bold);
        jLabel1.setFont(bold);
        jLabel2.setFont(bold);
        jLabel3.setFont(bold);
        jLabel4.setFont(bold);
        jLabel5.setFont(bold);
        jLabel6.setFont(bold);
        jLabel7.setFont(bold);

        javax.swing.JTextField[] readOnly = {
            idInput, nameInput, weightInput, birthDateInput, wingspanInput,
            habitatNameInput, habitatAreaInput, climateInput
        };
        for (javax.swing.JTextField f : readOnly) {
            f.setEnabled(true);
            f.setEditable(false);
            f.setBackground(Color.WHITE);
            f.setDisabledTextColor(Color.BLACK);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthDateInput;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton cleanBtn;
    private javax.swing.JTextField climateInput;
    private javax.swing.JButton computeBtn1;
    private javax.swing.JTextField habitatAreaInput;
    private javax.swing.JTextField habitatNameInput;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTextField weightInput;
    private javax.swing.JTextField wingspanInput;
    // End of variables declaration//GEN-END:variables
}
