/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zoo_animals.view;

import com.mycompany.zoo_animals.service.IAerialService;
import com.mycompany.zoo_animals.service.AerialService;
import com.mycompany.zoo_animals.service.IAquaticService;
import com.mycompany.zoo_animals.service.AquaticService;
import javax.swing.JOptionPane;

/**
 *
 * @author santiagomanchola
 */
public class GUIMain extends javax.swing.JFrame {
    
    IAerialService aerialService = new AerialService();
    IAquaticService aquaticService = new AquaticService();

    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        getAerial = new javax.swing.JMenuItem();
        getByIdAerial = new javax.swing.JMenuItem();
        createAerial = new javax.swing.JMenuItem();
        editAerial = new javax.swing.JMenuItem();
        deleteAerial = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        getAquatic = new javax.swing.JMenuItem();
        getByldAquatic = new javax.swing.JMenuItem();
        createAquatic = new javax.swing.JMenuItem();
        editAquatic = new javax.swing.JMenuItem();
        deleteAquatic = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jMenu9.setText("File");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar2.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Aereos");

        getAerial.setText("Ver todos");
        getAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAerialActionPerformed(evt);
            }
        });
        jMenu3.add(getAerial);

        getByIdAerial.setText("Buscar");
        getByIdAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getByIdAerialActionPerformed(evt);
            }
        });
        jMenu3.add(getByIdAerial);

        createAerial.setText("Crear");
        createAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAerialActionPerformed(evt);
            }
        });
        jMenu3.add(createAerial);

        editAerial.setText("Buscar y editar");
        editAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAerialActionPerformed(evt);
            }
        });
        jMenu3.add(editAerial);

        deleteAerial.setText("Buscar y eliminar");
        deleteAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAerialActionPerformed(evt);
            }
        });
        jMenu3.add(deleteAerial);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Acuaticos");

        getAquatic.setText("Ver todos");
        getAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(getAquatic);

        getByldAquatic.setText("Buscar");
        getByldAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getByldAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(getByldAquatic);

        createAquatic.setText("Crear");
        createAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(createAquatic);

        editAquatic.setText("Buscar y editar");
        editAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(editAquatic);

        deleteAquatic.setText("Buscar y eliminar");
        deleteAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(deleteAquatic);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ayuda");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Acerca de");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(this, "Desarrollado por Oscar Casallas, Andres Nieto, Jose Hidalgo y Santiago Manchola!");
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void getAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAerialActionPerformed
        GUIGetAerial gui = new GUIGetAerial(aerialService);
        gui.setVisible(true);
    }//GEN-LAST:event_getAerialActionPerformed

    private void getByIdAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getByIdAerialActionPerformed
        GUIGetAerialById gui = new GUIGetAerialById(aerialService);
        gui.setVisible(true);
    }//GEN-LAST:event_getByIdAerialActionPerformed

    private void createAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAerialActionPerformed
        GUICreateAerial gui = new GUICreateAerial(aerialService);
        gui.setVisible(true);
    }//GEN-LAST:event_createAerialActionPerformed

    private void editAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAerialActionPerformed
        GUIEditAerial gui = new GUIEditAerial(aerialService);
        gui.setVisible(true);
    }//GEN-LAST:event_editAerialActionPerformed

    private void deleteAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAerialActionPerformed
        GUIDeleteAerial gui = new GUIDeleteAerial(aerialService);
        gui.setVisible(true);
    }//GEN-LAST:event_deleteAerialActionPerformed

    private void getAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAquaticActionPerformed
        GUIGetAquatic gui = new GUIGetAquatic(aquaticService);
        gui.setVisible(true);
    }//GEN-LAST:event_getAquaticActionPerformed

    private void createAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAquaticActionPerformed
        GUICreateAquatic gui = new GUICreateAquatic(aquaticService);
        gui.setVisible(true);
    }//GEN-LAST:event_createAquaticActionPerformed

    private void getByldAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getByldAquaticActionPerformed
        GUIGetAquaticById gui = new GUIGetAquaticById(aquaticService);
        gui.setVisible(true);    }//GEN-LAST:event_getByldAquaticActionPerformed

    private void editAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAquaticActionPerformed
        GUIEditAquatic gui = new GUIEditAquatic(aquaticService);
        gui.setVisible(true);
    }//GEN-LAST:event_editAquaticActionPerformed

    private void deleteAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAquaticActionPerformed
        GUIDeleteAquatic gui = new GUIDeleteAquatic(aquaticService);
        gui.setVisible(true);
    }//GEN-LAST:event_deleteAquaticActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem createAerial;
    private javax.swing.JMenuItem createAquatic;
    private javax.swing.JMenuItem deleteAerial;
    private javax.swing.JMenuItem deleteAquatic;
    private javax.swing.JMenuItem editAerial;
    private javax.swing.JMenuItem editAquatic;
    private javax.swing.JMenuItem getAerial;
    private javax.swing.JMenuItem getAquatic;
    private javax.swing.JMenuItem getByIdAerial;
    private javax.swing.JMenuItem getByldAquatic;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
