/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zoo_animals.view;

import com.mycompany.zoo_animals.service.IAerialService;
import com.mycompany.zoo_animals.service.AerialService;
import com.mycompany.zoo_animals.service.IAquaticService;
import com.mycompany.zoo_animals.service.HabitatService;
import com.mycompany.zoo_animals.service.AquaticService;
import com.mycompany.zoo_animals.service.IHabitatService;
import javax.swing.JOptionPane;

/**
 *
 * @author santiagomanchola
 */
public class GUIMain extends javax.swing.JFrame {

    // Utilizando el patrón Singleton para los servicios
    IAerialService aerialService = AerialService.getInstance();
    IAquaticService aquaticService = AquaticService.getInstance();
    IHabitatService habitatService = HabitatService.getInstance();

    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
        setSize(900, 650);
        setLocationRelativeTo(null);
        // Mostrar el menú de Hábitat (anteriormente se ocultaba)
        if (jMenuHabitat != null) {
            jMenuHabitat.setVisible(true);
        }

        java.net.URL imageUrl = getClass().getResource("/images/zoo.png");
        if (imageUrl != null) {
            javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(imageUrl);

            java.awt.Image scaledImage = originalIcon.getImage().getScaledInstance(
                    jLabel2.getWidth(),
                    jLabel2.getHeight(),
                    java.awt.Image.SCALE_SMOOTH
            );

            jLabel2.setIcon(new javax.swing.ImageIcon(scaledImage));
            jLabel2.setText(""); // Quita el texto "jLabel2"
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        getAerial = new javax.swing.JMenuItem();
        getByIdAerial = new javax.swing.JMenuItem();
        createAerial = new javax.swing.JMenuItem();
        editAerial = new javax.swing.JMenuItem();
        deleteAerial = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        getAquatic = new javax.swing.JMenuItem();
        getByldAquatic = new javax.swing.JMenuItem();
        createAquatic = new javax.swing.JMenuItem();
        editAquatic = new javax.swing.JMenuItem();
        deleteAquatic = new javax.swing.JMenuItem();
        jMenuHabitat = new javax.swing.JMenu();
        getHabitat = new javax.swing.JMenuItem();
        getByIdHabitat = new javax.swing.JMenuItem();
        createHabitat = new javax.swing.JMenuItem();
        editHabitat = new javax.swing.JMenuItem();
        deleteHabitat = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenidos al Zoológico");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contentPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        contentPanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(contentPanel);

        jMenu6.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("Aereos");

        getAerial.setText("Ver todos");
        getAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAerialActionPerformed(evt);
            }
        });
        jMenu3.add(getAerial);

        getByIdAerial.setText("Buscar");
        getByIdAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getByIdAerialActionPerformed(evt);
            }
        });
        jMenu3.add(getByIdAerial);

        createAerial.setText("Crear");
        createAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAerialActionPerformed(evt);
            }
        });
        jMenu3.add(createAerial);

        editAerial.setText("Buscar y editar");
        editAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAerialActionPerformed(evt);
            }
        });
        jMenu3.add(editAerial);

        deleteAerial.setText("Buscar y eliminar");
        deleteAerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAerialActionPerformed(evt);
            }
        });
        jMenu3.add(deleteAerial);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Acuaticos");

        getAquatic.setText("Ver todos");
        getAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(getAquatic);

        getByldAquatic.setText("Buscar");
        getByldAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getByldAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(getByldAquatic);

        createAquatic.setText("Crear");
        createAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(createAquatic);

        editAquatic.setText("Buscar y editar");
        editAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(editAquatic);

        deleteAquatic.setText("Buscar y eliminar");
        deleteAquatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAquaticActionPerformed(evt);
            }
        });
        jMenu4.add(deleteAquatic);

        jMenuBar1.add(jMenu4);

        jMenuHabitat.setText("Hábitat");

        getHabitat.setText("Ver todos");
        getHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getHabitatActionPerformed(evt);
            }
        });
        jMenuHabitat.add(getHabitat);

        getByIdHabitat.setText("Buscar");
        getByIdHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getByIdHabitatActionPerformed(evt);
            }
        });
        jMenuHabitat.add(getByIdHabitat);

        createHabitat.setText("Crear");
        createHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHabitatActionPerformed(evt);
            }
        });
        jMenuHabitat.add(createHabitat);

        editHabitat.setText("Buscar y editar");
        editHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHabitatActionPerformed(evt);
            }
        });
        jMenuHabitat.add(editHabitat);

        deleteHabitat.setText("Buscar y eliminar");
        deleteHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHabitatActionPerformed(evt);
            }
        });
        jMenuHabitat.add(deleteHabitat);

        jMenuBar1.add(jMenuHabitat);

        jMenu5.setText("Ayuda");

        jMenuItem2.setText("Acerca de");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAerialActionPerformed
        GUIGetAerial gui = new GUIGetAerial(aerialService);
        gui.setVisible(true);
    }//GEN-LAST:event_getAerialActionPerformed

    private void getByIdAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getByIdAerialActionPerformed
        GUIGetAerialById gui = new GUIGetAerialById(aerialService);
        gui.setVisible(true);
    }//GEN-LAST:event_getByIdAerialActionPerformed

    private void createAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAerialActionPerformed
        GUICreateAerial gui = new GUICreateAerial(aerialService, habitatService);
        gui.setVisible(true);
    }//GEN-LAST:event_createAerialActionPerformed

    private void editAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAerialActionPerformed
        GUIEditAerial gui = new GUIEditAerial(aerialService, habitatService);
        gui.setVisible(true);
    }//GEN-LAST:event_editAerialActionPerformed

    private void deleteAerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAerialActionPerformed
        GUIDeleteAerial gui = new GUIDeleteAerial(aerialService);
        gui.setVisible(true);
    }//GEN-LAST:event_deleteAerialActionPerformed

    private void getAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAquaticActionPerformed
        GUIGetAquatic gui = new GUIGetAquatic(aquaticService);
        gui.setVisible(true);
    }//GEN-LAST:event_getAquaticActionPerformed

    private void createAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAquaticActionPerformed
        GUICreateAquatic gui = new GUICreateAquatic(aquaticService);
        gui.setVisible(true);
    }//GEN-LAST:event_createAquaticActionPerformed

    private void getByldAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getByldAquaticActionPerformed
        GUIGetAquaticById gui = new GUIGetAquaticById(aquaticService);
        gui.setVisible(true);    }//GEN-LAST:event_getByldAquaticActionPerformed

    private void editAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAquaticActionPerformed
        GUIEditAquatic gui = new GUIEditAquatic(aquaticService);
        gui.setVisible(true);
    }//GEN-LAST:event_editAquaticActionPerformed

    private void deleteAquaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAquaticActionPerformed
        GUIDeleteAquatic gui = new GUIDeleteAquatic(aquaticService);
        gui.setVisible(true);
    }//GEN-LAST:event_deleteAquaticActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea salir del sistema?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra toda la aplicación
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(this, "Desarrollado por Oscar Casallas, Andres Nieto, Jose Hidalgo y Santiago Manchola!");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenuItem createAerial;
    private javax.swing.JMenuItem createAquatic;
    private javax.swing.JMenuItem createHabitat;
    private javax.swing.JMenuItem deleteAerial;
    private javax.swing.JMenuItem deleteAquatic;
    private javax.swing.JMenuItem deleteHabitat;
    private javax.swing.JMenuItem editAerial;
    private javax.swing.JMenuItem editAquatic;
    private javax.swing.JMenuItem editHabitat;
    private javax.swing.JMenuItem getAerial;
    private javax.swing.JMenuItem getAquatic;
    private javax.swing.JMenuItem getByIdAerial;
    private javax.swing.JMenuItem getByIdHabitat;
    private javax.swing.JMenuItem getByldAquatic;
    private javax.swing.JMenuItem getHabitat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHabitat;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
    private void getHabitatActionPerformed(java.awt.event.ActionEvent evt) {
        GUIGetHabitat gui = new GUIGetHabitat(habitatService);
        gui.setVisible(true);
    }

    private void getByIdHabitatActionPerformed(java.awt.event.ActionEvent evt) {
        GUIGetHabitatById gui = new GUIGetHabitatById(habitatService);
        gui.setVisible(true);
    }

    private void createHabitatActionPerformed(java.awt.event.ActionEvent evt) {
        GUICreateHabitat gui = new GUICreateHabitat(habitatService);
        gui.setVisible(true);
    }

    private void editHabitatActionPerformed(java.awt.event.ActionEvent evt) {
        GUIEditHabitat gui = new GUIEditHabitat(habitatService);
        gui.setVisible(true);
    }

    private void deleteHabitatActionPerformed(java.awt.event.ActionEvent evt) {
        GUIDeleteHabitat gui = new GUIDeleteHabitat(habitatService);
        gui.setVisible(true);
    }
}
